version=0.1
[default.global.parameters]
stack_name = "LambdaTestFunction"

[default.deploy.parameters]
stack_name = "LambdaTestFunction"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default.build.parameters]
no_beta_features = true

[default.local_invoke.parameters]
region = "ap-northeast-1"